### ISSUE TITLE
Refresh or Keep home page after summarizing

### ISSUE THREAD

**Issue by huonglarne** [dinhanhx/text-summarizer#29]
This may even solve the problem in Issue #24 
Can anyone make the home page automatically reload right after summarizing so that all the fields to type in is blank again in case the user want to summarize again. This should also solve the problem in Cypress test. Besides, it would be nice if you include a cookie so that after refreshing the page, the interface is still dark/light as before.

**Comment by dinhanhx** [comment]
@DDHLong Can you try out your way?

**Comment by dinhanhx** [comment]
I have tried many ways. There are ways to keep the page not reload itself (on [Reddit](https://www.reddit.com/r/flask/comments/9kz1gd/ask_flask_how_do_i_submit_one_form_on_a_page/)) but I won't try it because it's time consuming and I have no time to learn that things.

Now the webapp have to reload itself.
